name: ROS2 Design
description: "Distilled design documents related to the ROS 2.0 effort"

baseurl: http://foote.github.io/design
repo: https://github.com/tfoote/design

oauth_client_id: efa6dd8eae9106381720

permalink: pretty

markdown: maruku
pygments: true

exclude:
 - CNAME
 - config.json
 - Gemfile
 - LICENSE
 - README.md
